import * as vscode from 'vscode';
import { createNote } from './fileManager';

export class CalendarViewProvider implements vscode.WebviewViewProvider {
    constructor(
        private readonly _extensionUri: vscode.Uri,
    ) { }

    public resolveWebviewView(
        webviewView: vscode.WebviewView,
        context: vscode.WebviewViewResolveContext,
        _token: vscode.CancellationToken,
    ) {
        webviewView.webview.options = {
            enableScripts: true,
            localResourceRoots: [this._extensionUri]
        };

        webviewView.webview.html = this._getWebviewContent(webviewView.webview);

        // Handle messages from the webview
        webviewView.webview.onDidReceiveMessage(
            async message => {
                switch (message.command) {
                    case 'dateClicked':
                        await createNote(message.date);
                        break;
                }
            },
            undefined,
            []
        );
    }

    private _getWebviewContent(webview: vscode.Webview): string {
        // Get paths to style and script files
        const cssPath = vscode.Uri.joinPath(this._extensionUri, 'media', 'styles', 'calendar.css');
        const jsPath = vscode.Uri.joinPath(this._extensionUri, 'media', 'scripts', 'calendar.js');

        // Convert to webview URIs
        const cssUri = webview.asWebviewUri(cssPath);
        const jsUri = webview.asWebviewUri(jsPath);
        
        // Create HTML directly (no file reading in web extensions)
        return `<!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Calmdown Calendar</title>
                <link rel="stylesheet" href="${cssUri}">
            </head>
            <body>
                <div class="container">
                    <div class="calendar-header">
                        <button id="prev-month">&lt;</button>
                        <div class="month-year" id="month-year">April 2025</div>
                        <button id="next-month">&gt;</button>
                    </div>
                    <div class="calendar" id="calendar">
                        <!-- Calendar will be generated by JS -->
                    </div>
                </div>
                <script src="${jsUri}"></script>
            </body>
            </html>`;
    }
}